version: 2
before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  # =====================================================================================
  # Linux build
  # =====================================================================================
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
      - v2
      - v3
      - v4
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/andresbott/etna/app/metainfo.Version={{.Version}}
      - -X github.com/andresbott/etna/app/metainfo.BuildTime={{.Date}}
      - -X github.com/andresbott/etna/app/metainfo.ShaVer={{.Commit}}
    binary: etna
    env:
      - >-
        {{- if eq .Arch "arm64" }}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm" }}CC=arm-linux-gnueabi-gcc{{- end }}    

  # =====================================================================================
  # Windows build
  # =====================================================================================
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
      - v3
      - v4
    ldflags:
      - -s -w
      - -X github.com/andresbott/etna/app/metainfo.Version={{.Version}}
      - -X github.com/andresbott/etna/app/metainfo.BuildTime={{.Date}}
      - -X github.com/andresbott/etna/app/metainfo.ShaVer={{.Commit}}
    flags:
      - -trimpath
    binary: etna

archives:
  - formats: [zip]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      etna-finance_
      {{- title .Os  }}_
      {{- if eq .Arch "amd64" }}x86_64_{{ .Amd64 }}
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - src: zarf/sample-config.yaml
        dst: config.yaml


# see full detail: https://goreleaser.com/customization/nfpm/
nfpms:
  -
    id: etna-finance
    package_name: etna-finance

    maintainer: "Andres Bott <contact@andresbott.com>"
    homepage: https://github.com/go-bumbu/todo-app
    description: |
      sample application for the go-bumbu framework
      license: LGPL3
    formats:
      - deb

    contents:
      # Basic file that applies to all packagers
      - src: zarf/sample-config.yaml
        dst: /etc/etna-finance/config.yaml
      - src: README.md
        dst: /usr/share/doc/etna-finance/README.md
      - src: LICENSE
        dst: /usr/share/doc/etna-finance/LICENSE

    # Version Prerelease.
    # Default is extracted from `version` if it is semver compatible.
    #    prerelease: snapshot

    #pacakge classification
    section: default
    priority: optional

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

