package main

var Accounts = []Provider{
	{
		Name:        "Cash Store",
		Description: "Stored in Cash",
		Accounts: []Account{
			{

				Name:        "Wallet",
				Description: "Physical wallet",
				Currency:    "CHF",
				Type:        "cash",
			},
		},
	},
	{
		Name:        "Main Bank",
		Description: "Sample provider",
		Accounts: []Account{
			{

				Name:        "Main Account",
				Description: "Primary checking",
				Currency:    "CHF",
				Type:        "checkin",
			},
			{
				Name:        "Eur expenses",
				Description: "",
				Currency:    "EUR",
				Type:        "checkin",
			},
		},
	},
	{
		Name:        "Secondary Bank",
		Description: "",
		Accounts: []Account{
			{
				Name:        "Another Bank",
				Description: "secondary checking",
				Currency:    "CHF",
				Type:        "checkin",
			},
		},
	},
}

var ExpenseCategories = []Category{
	{
		Name:        "Cost of living",
		Description: "Recuring cost of living",
		Children: []Category{
			{
				Name:        "Housing",
				Description: "Housing and home expenses",
				Children: []Category{
					{
						Name:        "Rent",
						Description: "Monthly rent payments",
					},
					{
						Name:        "Mortgage",
						Description: "Mortgage payments",
					},
					{
						Name:        "Utilities",
						Description: "Electricity, gas, water, internet",
					},
					{
						Name:        "Home Maintenance",
						Description: "Repairs and improvements",
					},
				},
			},
			{
				Name:        "Food",
				Description: "Food and dining expenses",
				Children: []Category{
					{
						Name:        "Groceries",
						Description: "Supermarket and food shopping",
					},
					{
						Name:        "Restaurants",
						Description: "Dining out and takeaway",
					},
					{
						Name:        "Coffee & Drinks",
						Description: "Coffee shops and beverages",
					},
				},
			},
			{
				Name:        "Transportation",
				Description: "Vehicle and travel expenses",
			},
		},
	},

	{
		Name:        "Health & Personal",
		Description: "Health and personal care",
		Children: []Category{
			{
				Name:        "Medical",
				Description: "Doctor visits and healthcare",
			},
			{
				Name:        "Pharmacy",
				Description: "Medications and pharmacy",
			},
			{
				Name:        "Personal Care",
				Description: "Haircuts, cosmetics, fitness",
			},
		},
	},
	{
		Name:        "Shopping",
		Description: "Shopping and purchases",
		Children: []Category{
			{
				Name:        "Clothing",
				Description: "Clothes and shoes",
			},
			{
				Name:        "Electronics",
				Description: "Phones, computers, gadgets",
			},
			{
				Name:        "Home & Garden",
				Description: "Furniture and home items",
			},
		},
	},
	{
		Name:        "Hobby",
		Description: "Entertainment and recreation",
		Children: []Category{
			{
				Name:        "Entertainment",
				Description: "Entertainment and recreation",
				Children: []Category{
					{
						Name:        "Streaming & Digital",
						Description: "Netflix, Spotify, games",
					},
					{
						Name:        "Events & Activities",
						Description: "Movies, concerts, sports",
					},
				},
			},
			{
				Name:        "DIY projects",
				Description: "",
				Children: []Category{
					{
						Name:        "PC",
						Description: "Pieces and Computer expenses",
					},
					{
						Name:        "Wood working",
						Description: "",
					},
				},
			},
		},
	},
}

var IncomeCategories = []Category{
	{
		Name:        "Employment",
		Description: "Work and employment income",
		Children: []Category{
			{
				Name:        "Salary",
				Description: "Regular salary and wages",
			},
			{
				Name:        "Bonuses",
				Description: "Performance bonuses and commissions",
			},
			{
				Name:        "Freelance",
				Description: "Freelance and contract work",
			},
		},
	},
	{
		Name:        "Investments",
		Description: "Investment income",
		Children: []Category{
			{
				Name:        "Dividends",
				Description: "Stock dividends",
			},
			{
				Name:        "Capital Gains",
				Description: "Investment profits",
			},
			{
				Name:        "Interest",
				Description: "Savings and bond interest",
			},
			{
				Name:        "Rental Income",
				Description: "Property rental income",
			},
		},
	},
}

var Entries = []EntryDefinition{
	// Monthly Income entries (repeated across 3 months)
	{
		Description:  "Monthly salary - current month",
		DaysDelta:    -1,
		Type:         "income",
		Amount:       4500.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Salary",
	},
	{
		Description:  "Monthly salary - last month",
		DaysDelta:    -31,
		Type:         "income",
		Amount:       4500.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Salary",
	},
	{
		Description:  "Monthly salary - two months ago",
		DaysDelta:    -61,
		Type:         "income",
		Amount:       4500.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Salary",
	},
	{
		Description:  "Performance bonus",
		DaysDelta:    -45,
		Type:         "income",
		Amount:       1200.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Bonuses",
	},
	{
		Description:  "Freelance web development project",
		DaysDelta:    -14,
		Type:         "income",
		Amount:       800.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Freelance",
	},
	{
		Description:  "Freelance mobile app project",
		DaysDelta:    -35,
		Type:         "income",
		Amount:       1200.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Freelance",
	},
	{
		Description:  "Freelance consulting work",
		DaysDelta:    -70,
		Type:         "income",
		Amount:       650.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Freelance",
	},
	{
		Description:  "Apple stock dividend",
		DaysDelta:    -7,
		Type:         "income",
		Amount:       125.30,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Dividends",
	},
	{
		Description:  "Microsoft stock dividend",
		DaysDelta:    -37,
		Type:         "income",
		Amount:       98.50,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Dividends",
	},
	{
		Description:  "Tesla stock capital gains",
		DaysDelta:    -21,
		Type:         "income",
		Amount:       650.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Capital Gains",
	},
	{
		Description:  "Bitcoin profit",
		DaysDelta:    -55,
		Type:         "income",
		Amount:       750.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Capital Gains",
	},
	{
		Description:  "Savings account interest",
		DaysDelta:    -32,
		Type:         "income",
		Amount:       45.20,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Interest",
	},
	{
		Description:  "Government bonds interest",
		DaysDelta:    -62,
		Type:         "income",
		Amount:       85.30,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Interest",
	},
	{
		Description:  "Apartment rental income",
		DaysDelta:    -3,
		Type:         "income",
		Amount:       1500.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Rental Income",
	},
	{
		Description:  "Apartment rental income",
		DaysDelta:    -33,
		Type:         "income",
		Amount:       1500.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Rental Income",
	},
	{
		Description:  "Apartment rental income",
		DaysDelta:    -63,
		Type:         "income",
		Amount:       1500.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Rental Income",
	},

	// Housing & Rent expenses (monthly recurring)
	{
		Description:  "Monthly rent payment",
		DaysDelta:    -1,
		Type:         "expense",
		Amount:       1200.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Rent",
	},
	{
		Description:  "Monthly rent payment",
		DaysDelta:    -31,
		Type:         "expense",
		Amount:       1200.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Rent",
	},
	{
		Description:  "Monthly rent payment",
		DaysDelta:    -61,
		Type:         "expense",
		Amount:       1200.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Rent",
	},
	{
		Description:  "Mortgage payment",
		DaysDelta:    -15,
		Type:         "expense",
		Amount:       1850.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Mortgage",
	},
	{
		Description:  "Mortgage payment",
		DaysDelta:    -45,
		Type:         "expense",
		Amount:       1850.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Mortgage",
	},
	{
		Description:  "Mortgage payment",
		DaysDelta:    -75,
		Type:         "expense",
		Amount:       1850.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Mortgage",
	},
	{
		Description:  "Electricity bill",
		DaysDelta:    -5,
		Type:         "expense",
		Amount:       120.45,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Utilities",
	},
	{
		Description:  "Gas heating bill",
		DaysDelta:    -25,
		Type:         "expense",
		Amount:       95.30,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Utilities",
	},
	{
		Description:  "Water bill",
		DaysDelta:    -18,
		Type:         "expense",
		Amount:       45.80,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Utilities",
	},
	{
		Description:  "Internet subscription",
		DaysDelta:    -8,
		Type:         "expense",
		Amount:       65.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Utilities",
	},
	{
		Description:  "Internet subscription",
		DaysDelta:    -38,
		Type:         "expense",
		Amount:       65.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Utilities",
	},
	{
		Description:  "Internet subscription",
		DaysDelta:    -68,
		Type:         "expense",
		Amount:       65.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Utilities",
	},
	{
		Description:  "Plumbing repair",
		DaysDelta:    -42,
		Type:         "expense",
		Amount:       285.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Home Maintenance",
	},
	{
		Description:  "Roof tiles replacement",
		DaysDelta:    -78,
		Type:         "expense",
		Amount:       1500.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Home Maintenance",
	},

	// Food expenses
	{
		Description:  "Grocery shopping at Coop",
		DaysDelta:    -2,
		Type:         "expense",
		Amount:       85.50,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Groceries",
	},
	{
		Description:  "Weekly groceries at Migros",
		DaysDelta:    -9,
		Type:         "expense",
		Amount:       92.30,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Organic food shopping",
		DaysDelta:    -16,
		Type:         "expense",
		Amount:       125.60,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Bulk shopping at Costco",
		DaysDelta:    -23,
		Type:         "expense",
		Amount:       156.75,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Fresh market vegetables",
		DaysDelta:    -30,
		Type:         "expense",
		Amount:       45.20,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Groceries",
	},
	{
		Description:  "Weekly groceries",
		DaysDelta:    -37,
		Type:         "expense",
		Amount:       78.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Special occasion groceries",
		DaysDelta:    -44,
		Type:         "expense",
		Amount:       110.40,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Weekend groceries",
		DaysDelta:    -51,
		Type:         "expense",
		Amount:       89.20,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Monthly bulk groceries",
		DaysDelta:    -58,
		Type:         "expense",
		Amount:       145.80,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Gourmet ingredients",
		DaysDelta:    -65,
		Type:         "expense",
		Amount:       67.30,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Weekly groceries",
		DaysDelta:    -72,
		Type:         "expense",
		Amount:       95.70,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Groceries",
	},
	{
		Description:  "Emergency groceries",
		DaysDelta:    -79,
		Type:         "expense",
		Amount:       52.40,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Groceries",
	},

	// Restaurants & Dining
	{
		Description:  "Dinner at Italian restaurant",
		DaysDelta:    -4,
		Type:         "expense",
		Amount:       75.60,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Lunch at sushi place",
		DaysDelta:    -11,
		Type:         "expense",
		Amount:       32.50,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Pizza delivery",
		DaysDelta:    -18,
		Type:         "expense",
		Amount:       28.90,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Business lunch",
		DaysDelta:    -25,
		Type:         "expense",
		Amount:       45.80,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Weekend brunch",
		DaysDelta:    -32,
		Type:         "expense",
		Amount:       38.70,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Thai food takeout",
		DaysDelta:    -39,
		Type:         "expense",
		Amount:       24.30,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Anniversary dinner",
		DaysDelta:    -46,
		Type:         "expense",
		Amount:       125.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Fast food lunch",
		DaysDelta:    -53,
		Type:         "expense",
		Amount:       12.50,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Indian restaurant dinner",
		DaysDelta:    -60,
		Type:         "expense",
		Amount:       42.80,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Restaurants",
	},
	{
		Description:  "Chinese takeaway",
		DaysDelta:    -67,
		Type:         "expense",
		Amount:       19.90,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Restaurants",
	},

	// Coffee & Drinks
	{
		Description:  "Coffee at Starbucks",
		DaysDelta:    -1,
		Type:         "expense",
		Amount:       4.50,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Coffee & Drinks",
	},
	{
		Description:  "Morning latte",
		DaysDelta:    -6,
		Type:         "expense",
		Amount:       5.20,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Coffee & Drinks",
	},
	{
		Description:  "Afternoon coffee break",
		DaysDelta:    -13,
		Type:         "expense",
		Amount:       3.80,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Coffee & Drinks",
	},
	{
		Description:  "Coffee beans for home",
		DaysDelta:    -20,
		Type:         "expense",
		Amount:       24.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Coffee & Drinks",
	},
	{
		Description:  "Meeting coffee",
		DaysDelta:    -27,
		Type:         "expense",
		Amount:       7.60,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Coffee & Drinks",
	},
	{
		Description:  "Energy drinks",
		DaysDelta:    -34,
		Type:         "expense",
		Amount:       8.40,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Coffee & Drinks",
	},
	{
		Description:  "Local cafe visit",
		DaysDelta:    -41,
		Type:         "expense",
		Amount:       6.30,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Coffee & Drinks",
	},
	{
		Description:  "Premium coffee subscription",
		DaysDelta:    -48,
		Type:         "expense",
		Amount:       29.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Coffee & Drinks",
	},

	// Transportation
	{
		Description:  "Gas station fill-up",
		DaysDelta:    -4,
		Type:         "expense",
		Amount:       65.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Transportation",
	},
	{
		Description:  "Public transport monthly pass",
		DaysDelta:    -12,
		Type:         "expense",
		Amount:       85.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Transportation",
	},
	{
		Description:  "Taxi ride home",
		DaysDelta:    -19,
		Type:         "expense",
		Amount:       25.80,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Transportation",
	},
	{
		Description:  "Car maintenance service",
		DaysDelta:    -26,
		Type:         "expense",
		Amount:       285.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Transportation",
	},
	{
		Description:  "Airport parking",
		DaysDelta:    -33,
		Type:         "expense",
		Amount:       45.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Transportation",
	},
	{
		Description:  "Uber ride to meeting",
		DaysDelta:    -40,
		Type:         "expense",
		Amount:       18.50,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Transportation",
	},
	{
		Description:  "Car insurance premium",
		DaysDelta:    -47,
		Type:         "expense",
		Amount:       125.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Transportation",
	},
	{
		Description:  "Train ticket for trip",
		DaysDelta:    -54,
		Type:         "expense",
		Amount:       89.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Transportation",
	},

	// Health & Personal Care
	{
		Description:  "Doctor visit copay",
		DaysDelta:    -10,
		Type:         "expense",
		Amount:       45.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Medical",
	},
	{
		Description:  "Annual health checkup",
		DaysDelta:    -35,
		Type:         "expense",
		Amount:       180.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Medical",
	},
	{
		Description:  "Specialist consultation",
		DaysDelta:    -58,
		Type:         "expense",
		Amount:       95.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Medical",
	},
	{
		Description:  "Prescription medication",
		DaysDelta:    -7,
		Type:         "expense",
		Amount:       28.50,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Pharmacy",
	},
	{
		Description:  "Vitamins and supplements",
		DaysDelta:    -22,
		Type:         "expense",
		Amount:       45.20,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Pharmacy",
	},
	{
		Description:  "Pain relief medication",
		DaysDelta:    -49,
		Type:         "expense",
		Amount:       12.80,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Pharmacy",
	},
	{
		Description:  "Haircut at salon",
		DaysDelta:    -14,
		Type:         "expense",
		Amount:       35.00,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Personal Care",
	},
	{
		Description:  "Gym membership",
		DaysDelta:    -28,
		Type:         "expense",
		Amount:       65.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Personal Care",
	},
	{
		Description:  "Skincare products",
		DaysDelta:    -43,
		Type:         "expense",
		Amount:       78.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Personal Care",
	},
	{
		Description:  "Yoga class package",
		DaysDelta:    -56,
		Type:         "expense",
		Amount:       120.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Personal Care",
	},

	// Shopping & Clothing
	{
		Description:  "New winter jacket",
		DaysDelta:    -12,
		Type:         "expense",
		Amount:       120.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Clothing",
	},
	{
		Description:  "Business shirts",
		DaysDelta:    -29,
		Type:         "expense",
		Amount:       85.60,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Clothing",
	},
	{
		Description:  "Running shoes",
		DaysDelta:    -44,
		Type:         "expense",
		Amount:       135.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Clothing",
	},
	{
		Description:  "Summer dress",
		DaysDelta:    -67,
		Type:         "expense",
		Amount:       68.50,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Clothing",
	},
	{
		Description:  "New smartphone",
		DaysDelta:    -21,
		Type:         "expense",
		Amount:       850.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Electronics",
	},
	{
		Description:  "Laptop upgrade",
		DaysDelta:    -52,
		Type:         "expense",
		Amount:       1250.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Electronics",
	},
	{
		Description:  "Wireless headphones",
		DaysDelta:    -73,
		Type:         "expense",
		Amount:       189.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Electronics",
	},
	{
		Description:  "Kitchen appliance",
		DaysDelta:    -17,
		Type:         "expense",
		Amount:       245.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Home & Garden",
	},
	{
		Description:  "Garden plants and supplies",
		DaysDelta:    -36,
		Type:         "expense",
		Amount:       95.30,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Home & Garden",
	},
	{
		Description:  "Living room lamp",
		DaysDelta:    -59,
		Type:         "expense",
		Amount:       78.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Home & Garden",
	},

	// Entertainment & Hobbies
	{
		Description:  "Netflix subscription",
		DaysDelta:    -3,
		Type:         "expense",
		Amount:       16.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Streaming & Digital",
	},
	{
		Description:  "Spotify premium",
		DaysDelta:    -33,
		Type:         "expense",
		Amount:       12.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Streaming & Digital",
	},
	{
		Description:  "Gaming subscription",
		DaysDelta:    -63,
		Type:         "expense",
		Amount:       24.99,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Streaming & Digital",
	},
	{
		Description:  "Concert tickets",
		DaysDelta:    -15,
		Type:         "expense",
		Amount:       125.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Events & Activities",
	},
	{
		Description:  "Movie theater night",
		DaysDelta:    -24,
		Type:         "expense",
		Amount:       32.50,
		ProviderName: "Cash Store",
		AccountName:  "Wallet",
		CategoryName: "Events & Activities",
	},
	{
		Description:  "Sports event tickets",
		DaysDelta:    -50,
		Type:         "expense",
		Amount:       89.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Events & Activities",
	},
	{
		Description:  "Computer parts upgrade",
		DaysDelta:    -16,
		Type:         "expense",
		Amount:       385.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "PC",
	},
	{
		Description:  "New graphics card",
		DaysDelta:    -41,
		Type:         "expense",
		Amount:       650.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "PC",
	},
	{
		Description:  "Wood for DIY project",
		DaysDelta:    -23,
		Type:         "expense",
		Amount:       145.60,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Wood working",
	},
	{
		Description:  "Woodworking tools",
		DaysDelta:    -57,
		Type:         "expense",
		Amount:       289.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Wood working",
	},

	// Transfer entries - realistic money movements
	{
		Description:    "Transfer to EUR account for vacation",
		DaysDelta:      -15,
		Type:           "transfer",
		OriginAmount:   500.00,
		OriginProvider: "Main Bank",
		OriginAccount:  "Main Account",
		TargetAmount:   500.00,
		TargetProvider: "Main Bank",
		TargetAccount:  "Eur expenses",
	},
	{
		Description:    "Cash withdrawal for weekend",
		DaysDelta:      -3,
		Type:           "transfer",
		OriginAmount:   100.00,
		OriginProvider: "Main Bank",
		OriginAccount:  "Main Account",
		TargetAmount:   100.00,
		TargetProvider: "Cash Store",
		TargetAccount:  "Wallet",
	},
	{
		Description:    "Emergency cash withdrawal",
		DaysDelta:      -25,
		Type:           "transfer",
		OriginAmount:   200.00,
		OriginProvider: "Main Bank",
		OriginAccount:  "Main Account",
		TargetAmount:   200.00,
		TargetProvider: "Cash Store",
		TargetAccount:  "Wallet",
	},
	{
		Description:    "Transfer to secondary bank",
		DaysDelta:      -38,
		Type:           "transfer",
		OriginAmount:   1000.00,
		OriginProvider: "Main Bank",
		OriginAccount:  "Main Account",
		TargetAmount:   1000.00,
		TargetProvider: "Secondary Bank",
		TargetAccount:  "Another Bank",
	},
	{
		Description:    "Holiday money exchange",
		DaysDelta:      -48,
		Type:           "transfer",
		OriginAmount:   800.00,
		OriginProvider: "Main Bank",
		OriginAccount:  "Main Account",
		TargetAmount:   800.00,
		TargetProvider: "Main Bank",
		TargetAccount:  "Eur expenses",
	},
	{
		Description:    "Weekend cash top-up",
		DaysDelta:      -55,
		Type:           "transfer",
		OriginAmount:   150.00,
		OriginProvider: "Main Bank",
		OriginAccount:  "Main Account",
		TargetAmount:   150.00,
		TargetProvider: "Cash Store",
		TargetAccount:  "Wallet",
	},
	{
		Description:    "Investment transfer",
		DaysDelta:      -71,
		Type:           "transfer",
		OriginAmount:   2000.00,
		OriginProvider: "Main Bank",
		OriginAccount:  "Main Account",
		TargetAmount:   2000.00,
		TargetProvider: "Secondary Bank",
		TargetAccount:  "Another Bank",
	},

	// Additional entries to reach exactly 150
	{
		Description:  "Dental cleaning",
		DaysDelta:    -66,
		Type:         "expense",
		Amount:       150.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Medical",
	},
	{
		Description:  "Book purchase",
		DaysDelta:    -51,
		Type:         "expense",
		Amount:       25.90,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Entertainment",
	},
	{
		Description:  "Side consulting income",
		DaysDelta:    -77,
		Type:         "income",
		Amount:       450.00,
		ProviderName: "Main Bank",
		AccountName:  "Main Account",
		CategoryName: "Freelance",
	},
}
